param(
    [string]$InstallRoot = "F:\Program Files\MetaTrader 5 EXNESS",
    [string]$TerminalDataPath = "C:\Users\3762\AppData\Roaming\MetaQuotes\Terminal\B695BCB6C1E6864B6D96307B87B29F16",
    [switch]$RunTester
)

$ErrorActionPreference = "Stop"

$Workspace = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$MetaEditor = Join-Path $InstallRoot "MetaEditor64.exe"
$Terminal = Join-Path $InstallRoot "terminal64.exe"
$ExpertsDir = Join-Path $TerminalDataPath "MQL5\Experts\Advisors"
$TesterProfileDir = Join-Path $TerminalDataPath "MQL5\Profiles\Tester"
$LogDir = Join-Path $Workspace "ea_alignment_logs"
$TerminalRoot = Split-Path -Parent $TerminalDataPath
$MetaQuotesRoot = Split-Path -Parent $TerminalRoot
$TerminalId = Split-Path -Leaf $TerminalDataPath
$TesterDataPath = Join-Path (Join-Path $MetaQuotesRoot "Tester") $TerminalId

if (-not (Test-Path -LiteralPath $MetaEditor)) {
    throw "MetaEditor64.exe not found: $MetaEditor"
}
if (-not (Test-Path -LiteralPath $Terminal)) {
    throw "terminal64.exe not found: $Terminal"
}

New-Item -ItemType Directory -Force -Path $ExpertsDir, $TesterProfileDir, $LogDir | Out-Null

$Strategies = @(
    @{
        Name = "1H_M30_4H"
        DirPrefix = "1H_M30_4H"
        Expert = "1H_M30_4H_Strategy_EA"
        SetFile = "1H_M30_4H_Strategy_EA.mt5_raw_research_20260725.set"
        FromDate = "2020.01.02"
        ToDate = "2023.12.29"
    },
    @{
        Name = "2H_M30_6H"
        DirPrefix = "2H_M30_6H"
        Expert = "2H_M30_6H_Strategy_EA"
        SetFile = "2H_M30_6H_Strategy_EA.mt5_raw_research_20260725.set"
        FromDate = "2024.01.01"
        ToDate = "2026.07.24"
    }
)

function Resolve-StrategyDir {
    param([hashtable]$Strategy)
    $matches = Get-ChildItem -LiteralPath $Workspace -Directory |
        Where-Object { $_.Name -like "$($Strategy.DirPrefix)*" } |
        Sort-Object Name
    if (-not $matches -or $matches.Count -lt 1) {
        throw "Strategy directory not found for prefix: $($Strategy.DirPrefix)"
    }
    return $matches[0].FullName
}

function Build-TesterConfig {
    param(
        [hashtable]$Strategy,
        [string]$StrategyDir,
        [string]$SetSource,
        [string]$IniPath,
        [string]$ReportPath
    )

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $IniPath), (Split-Path -Parent $ReportPath) | Out-Null

    $header = @(
        "; Generated by scripts/mt5/ea_alignment_runner.ps1",
        "; Strategy: $($Strategy.Name)",
        "[Tester]",
        "Expert=Advisors\$($Strategy.Expert).ex5",
        "Symbol=XAUUSDm",
        "Period=M30",
        "Optimization=0",
        "Model=0",
        "FromDate=$($Strategy.FromDate)",
        "ToDate=$($Strategy.ToDate)",
        "ForwardMode=0",
        "Deposit=500",
        "Currency=USD",
        "ProfitInPips=0",
        "Leverage=2000",
        "ExecutionMode=0",
        "OptimizationCriterion=0",
        "Visual=0",
        "ReplaceReport=1",
        "ShutdownTerminal=1",
        "Report=$ReportPath",
        "",
        "[TesterInputs]"
    )

    $inputs = Get-Content -LiteralPath $SetSource | Where-Object {
        $line = $_.Trim()
        $line -and -not $line.StartsWith(";")
    }

    Set-Content -LiteralPath $IniPath -Value ($header + $inputs) -Encoding ASCII
}

function Get-TesterFilesDirs {
    if (-not (Test-Path -LiteralPath $TesterDataPath)) {
        return @()
    }

    $agents = Get-ChildItem -LiteralPath $TesterDataPath -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "Agent-*" }
    $dirs = @()
    foreach ($agent in $agents) {
        $filesDir = Join-Path $agent.FullName "MQL5\Files"
        if (Test-Path -LiteralPath $filesDir) {
            $dirs += $filesDir
        }
    }
    return $dirs
}

function Clear-TesterExports {
    param([hashtable]$Strategy)

    $prefix = "$($Strategy.Name)_strategy_"
    foreach ($filesDir in Get-TesterFilesDirs) {
        Get-ChildItem -LiteralPath $filesDir -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "$prefix*" } |
            Remove-Item -Force
    }
}

function Copy-TesterExports {
    param(
        [hashtable]$Strategy,
        [string]$AlignmentDir
    )

    $prefix = "$($Strategy.Name)_strategy_"
    $wanted = @(
        "trade_ledger.csv",
        "deal_history.csv",
        "signals_export.csv",
        "m15_entry_diag.csv"
    )
    $copied = 0
    foreach ($filesDir in Get-TesterFilesDirs) {
        foreach ($suffix in $wanted) {
            $source = Join-Path $filesDir "$prefix$suffix"
            if (Test-Path -LiteralPath $source) {
                $dest = Join-Path $AlignmentDir (Split-Path -Leaf $source)
                Copy-Item -LiteralPath $source -Destination $dest -Force
                $copied += 1
                Write-Host "[$($Strategy.Name)] tester export copied: $dest"
            }
        }
    }

    if ($copied -eq 0) {
        Write-Host "[$($Strategy.Name)] tester exports missing after run under: $TesterDataPath"
    }
}

foreach ($strategy in $Strategies) {
    $strategyDir = Resolve-StrategyDir -Strategy $strategy
    $sourceMq5 = Join-Path $strategyDir "auto_trade\$($strategy.Expert).mq5"
    $sourceSet = Join-Path $strategyDir "auto_trade\$($strategy.SetFile)"
    if (-not (Test-Path -LiteralPath $sourceMq5)) {
        throw "EA source not found: $sourceMq5"
    }
    if (-not (Test-Path -LiteralPath $sourceSet)) {
        throw "Research set not found: $sourceSet"
    }

    $destMq5 = Join-Path $ExpertsDir "$($strategy.Expert).mq5"
    $destSet = Join-Path $TesterProfileDir "$($strategy.SetFile)"
    $destCanonicalSet = Join-Path $TesterProfileDir "$($strategy.Expert).set"
    Copy-Item -LiteralPath $sourceMq5 -Destination $destMq5 -Force
    Copy-Item -LiteralPath $sourceSet -Destination $destSet -Force
    Copy-Item -LiteralPath $sourceSet -Destination $destCanonicalSet -Force

    $compileLog = Join-Path $LogDir "$($strategy.Expert).compile.log"
    $compileArgs = "/compile:`"$destMq5`" /log:`"$compileLog`""
    $process = Start-Process -FilePath $MetaEditor -ArgumentList $compileArgs -Wait -PassThru -WindowStyle Hidden
    $ex5 = Join-Path $ExpertsDir "$($strategy.Expert).ex5"
    $compiled = Test-Path -LiteralPath $ex5

    $alignmentDir = Join-Path $strategyDir "data\validation\ea_alignment"
    New-Item -ItemType Directory -Force -Path $alignmentDir | Out-Null
    $iniPath = Join-Path $LogDir "$($strategy.Expert).mt5_raw_research_20260725.ini"
    $reportPath = Join-Path $LogDir "$($strategy.Expert).tester_report.xml"
    if (Test-Path -LiteralPath $reportPath) {
        Remove-Item -LiteralPath $reportPath -Force
    }
    Build-TesterConfig -Strategy $strategy -StrategyDir $strategyDir -SetSource $sourceSet -IniPath $iniPath -ReportPath $reportPath

    Write-Host "[$($strategy.Name)] deployed mq5: $destMq5"
    Write-Host "[$($strategy.Name)] deployed set: $destSet"
    Write-Host "[$($strategy.Name)] compile exit code: $($process.ExitCode); ex5 exists: $compiled; log: $compileLog"
    Write-Host "[$($strategy.Name)] tester ini: $iniPath"
    Write-Host "[$($strategy.Name)] tester report: $reportPath"

    if ($RunTester) {
        Clear-TesterExports -Strategy $strategy
        $testerArgs = "/config:`"$iniPath`""
        $tester = Start-Process -FilePath $Terminal -ArgumentList $testerArgs -Wait -PassThru -WindowStyle Hidden
        Write-Host "[$($strategy.Name)] terminal tester exit code: $($tester.ExitCode)"
        Copy-TesterExports -Strategy $strategy -AlignmentDir $alignmentDir
        if (Test-Path -LiteralPath $reportPath) {
            $alignmentReport = Join-Path $alignmentDir "$($strategy.Expert).tester_report.xml"
            Copy-Item -LiteralPath $reportPath -Destination $alignmentReport -Force
            Write-Host "[$($strategy.Name)] tester report copied: $alignmentReport"
        } else {
            Write-Host "[$($strategy.Name)] tester report missing after run: $reportPath"
        }
    }
}
